# Generated by Django 3.0.5 on 2023-01-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20230129_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='webex_link',
            field=models.URLField(blank=True),
        ),
    ]
