# Generated by Django 3.0.5 on 2023-01-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_event_webex_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
