# Generated by Django 3.0.5 on 2023-01-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_event_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageimage',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
