# Generated by Django 3.0.5 on 2023-01-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20230130_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('link1', models.URLField()),
                ('link2', models.URLField()),
                ('link3', models.URLField()),
                ('link4', models.URLField()),
            ],
        ),
    ]
